language: node_js
node_js:
- '6'
- 4
sudo: false
addons:
  apt:
    sources: [ 'ubuntu-toolchain-r-test' ]
    packages: [ 'libstdc++-5-dev' ]
env:
  global:
  - secure: rFbJCcDbGQtC+PGL2NU/hGkEuzDdWL7AukuhqYBE2VcfCNsohc9EiIhLVrW5VTggLX/Eo8AEiUSIEGlto9RWkuF5Rh2SrA70gSMdm6gdEjHncJCR6yxXqJs5R6evC33k1xtfD7yQ/Ove+FXjyxfw4g6wYH40wGAZhO+fwGJDVdw=
  - secure: W1kOjO5OHVV4RCMpLua1O0WW9Is1Cu21vbmHdtbTMpQ6jusnqhETorqDlFmPGpW2oM7SJwcMRohteODte81/UWkR63ZzeSyPJXKBz73xgEVo4A2KIB2xeCnm0M6LZYQNSPYe1+NcuMm9r8j8zlHN7f2Z+lvxUm7zgx0s7PP+Zmk=
  - secure: uLTEYEfOuF5VidH9fOhOdxly/9ChkAwTKw7DZltmiNfy+QZ5QmDfXIgVj0hJRfeUFPd3+r+WwL68nEFj8fG9SCAAHeYUR9ewEwKkpZ0141zF7PpgftFWuLk64YPYNgd+R4wfdS3I63OSHQWpwOykZEcd3GBVIuHopt9At+KiyB8=
