version: 2

step-library:
  - &install-node
      run:
        name: Install node
        command: |
          set +e
          touch $BASH_ENV
          curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
          echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
          echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
          echo 'nvm install v4' >> $BASH_ENV
          echo 'nvm alias default v4' >> $BASH_ENV

  - &build-and-test
      run:
        name: Build and test
        command: |
          npm install
          npm test

jobs:
  build-osx:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - *install-node
      - *build-and-test

  build-linux:
    machine: true
    steps:
      - checkout
      - run:
          name: libstdc++ upgrade
          command: |
            sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
            sudo apt-get update -y
            sudo apt-get install -y libstdc++6
      - *install-node
      - *build-and-test


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-osx
      - build-linux